server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: dockerTestApp

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true